name: Codebase Workflow

# To run this workflow, all you need to do is push to main branch
on:
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      WORKING_DIRECTORY: codebase/rdicidr-0.1.0 # change this to the directory with the source

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'  # Use the Node.js version you need

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm install

      - name: Linter (ESLint)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run lint

      - name: Formatter (Prettier)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run prettier

      - name: Test (Jest)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: CI=true npm run test

      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run build
